# Generated by Django 4.0.5 on 2023-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
