# Generated by Django 4.0.5 on 2023-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unexploredHimalayas', '0002_alter_locations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
