# Generated by Django 4.0.5 on 2023-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unexploredHimalayas', '0003_alter_locations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
